jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  
securityRealm:
  local:
    allowsSignup: false
    users:
      - id: "vaugie_g"
        name: "Garance"
        password: "${USER_VAUGIE_G_PASSWORD}"
      - id: "chocolateen"
        name: "Hugo"
        password: "${USER_CHOCOLATEEN_PASSWORD}"
      - id: "i_dont_know"
        name: "Jeremy"
        password: "${USER_I_DONT_KNOW_PASSWORD}"
      - id: "nasso"
        name: "Nassim"
        password: "${USER_NASSO_PASSWORD}"

  authorizationStrategy:
    roleBased:
      roles:
        - role:
            name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignedSIDs:
              - "chocolateen"
        - role:
            name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Job/Build"
              - "Job/Workspace"
            assignedSIDs:
              - "i_dont_know"
        - role:
            name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Configure"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Cancel"
            assignedSIDs:
              - "vaugie_g"
        - role:
            name: "assist"
            description: "Assistant"
            permissions:
              - "Job/Read"
              - "Job/Workspace"
            assignedSIDs:
              - "nasso"
unclassified:
  casCGlobalConfig:
    configurationPath: "/var/jenkins_home/configuration.yml"
jobs:
  - file: /var/jenkins_home/job_dsl.groovy